# Site settings
# title: Butane Jekyll Theme
#description: >
#    Batyr's Notes
author: oneturkmen
email: youemail@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oneturkmen.github.io" # the base hostname & protocol for your site
github_username:  oneturkmen
linkedin_username: nuryyev

# Build settings
include: [_pages, _assets]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
